# permissions for end users to edit processorcontrols.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: processorcontrol-editor-role
rules:
- apiGroups:
  - nifi.orange.com
  resources:
  - processorcontrols
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nifi.orange.com
  resources:
  - processorcontrols/status
  verbs:
  - get
